-- Migration V2: Add security configuration columns to domains table
ALTER TABLE domains ADD COLUMN IF NOT EXISTS dkim_enabled BOOLEAN DEFAULT TRUE;
ALTER TABLE domains ADD COLUMN IF NOT EXISTS spf_enabled BOOLEAN DEFAULT TRUE;
ALTER TABLE domains ADD COLUMN IF NOT EXISTS dmarc_enabled BOOLEAN DEFAULT TRUE;
ALTER TABLE domains ADD COLUMN IF NOT EXISTS dmarc_policy TEXT;
ALTER TABLE domains ADD COLUMN IF NOT EXISTS dmarc_p_percentage INTEGER DEFAULT 0;
ALTER TABLE domains ADD COLUMN IF NOT EXISTS dkim_key_size INTEGER DEFAULT 2048;
ALTER TABLE domains ADD COLUMN IF NOT EXISTS dkim_signing_algorithm TEXT DEFAULT 'rsa-sha256';
ALTER TABLE domains ADD COLUMN IF NOT EXISTS spf_record TEXT;
ALTER TABLE domains ADD COLUMN IF NOT EXISTS dmarc_rua TEXT;
ALTER TABLE domains ADD COLUMN IF NOT EXISTS dmarc_ruf TEXT;
